ServerTokens Prod
ServerSignature Off
TraceEnable Off
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 2
Timeout 60
LimitRequestBody 31457280
<Directory "/var/www/html">
    Options -Indexes
</Directory>
