package testutil

func BaseEnvValues(scope string) map[string]string {
	return map[string]string{
		"ADMIN_PASSWORD":        "admin-secret",
		"ADMIN_USERNAME":        "admin",
		"APP_PORT":              "18080",
		"BACKUP_NAME_PREFIX":    "espocrm-" + scope,
		"BACKUP_RETENTION_DAYS": "7",
		"BACKUP_ROOT":           "./backups/" + scope,
		"COMPOSE_PROJECT_NAME":  "espocrm-" + scope,
		"DAEMON_CPUS":           "0.50",
		"DAEMON_MEM_LIMIT":      "256m",
		"DAEMON_PIDS_LIMIT":     "128",
		"DB_CPUS":               "1.00",
		"DB_MEM_LIMIT":          "512m",
		"DB_NAME":               "espocrm",
		"DB_PASSWORD":           "db-secret",
		"DB_PIDS_LIMIT":         "256",
		"DB_ROOT_PASSWORD":      "root-secret",
		"DB_STORAGE_DIR":        "./runtime/" + scope + "/db",
		"DB_USER":               "espocrm",
		"DOCKER_LOG_MAX_FILE":   "5",
		"DOCKER_LOG_MAX_SIZE":   "10m",
		"ESPO_CONTOUR":          scope,
		"ESPO_CPUS":             "1.00",
		"ESPO_DEFAULT_LANGUAGE": "ru_RU",
		"ESPO_LOGGER_LEVEL":     "INFO",
		"ESPO_MEM_LIMIT":        "512m",
		"ESPO_PIDS_LIMIT":       "256",
		"ESPO_HELPER_IMAGE":     "alpine:3.20",
		"ESPO_RUNTIME_GID":      "33",
		"ESPO_RUNTIME_UID":      "33",
		"ESPO_STORAGE_DIR":      "./runtime/" + scope + "/espo",
		"ESPO_TIME_ZONE":        "Europe/Moscow",
		"ESPOCRM_IMAGE":         "espocrm/espocrm:9.3.4-apache",
		"MARIADB_TAG":           "10.11",
		"MIN_FREE_DISK_MB":      "1",
		"SITE_URL":              "http://127.0.0.1:18080",
		"WS_CPUS":               "0.50",
		"WS_MEM_LIMIT":          "256m",
		"WS_PIDS_LIMIT":         "128",
		"WS_PORT":               "18081",
		"WS_PUBLIC_URL":         "ws://127.0.0.1:18081",
	}
}
